#!/bin/bash
count=0
customer_logpath=($(cat ps.txt |tr " " "\n" |grep "config.default.filepath"|sed 's/.*path=\(.*\)$/\1/g' |sed 's/conf.*/ /g')) ;
customer_name=($(cat ps.txt |tr " " "\n" |grep "config.default.filepath"|sed 's/.*clients\(.*\)$/\1/g'|sed 's@/@ @g'|awk '{print $1}'));
while [ $count -lt ${#customer_name[@]} ]
do
sed -i '1 i- type\\: log\n enabled: true\n paths:\n - '${customer_logpath[$count]}'SCM.log\n - '${customer_logpath[$count]}'catalina.out\n fields:\n customer: '${customer_name[$count]}'\nfields_under_root: true"' /etc/filebeat/filebeat.yml
((count++))
done

